#!/usr/bin/env bash
# Redirect to another page
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html
txt="\n\tlocation ~/redirect_me/ {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"
sed -i '/\tserver_name _;/a location /redirect_me/ { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
service nginx restart
