#!/usr/bin/env bash
# Manage the manage_my_process script
case "$1" in
	start)
		sudo -b sh manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -f "sudo -b sh manage_my_process"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -f "sudo -b sh manage_my_process"
		rm /var/run/my_process.pid
		sudo -b sh manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
