#!/usr/bin/env bash
# Manage the manage_my_process script
if [ "$1" = "start" ]; then
	sudo -b sh manage_my_process
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
	pkill -f "sudo -b sh manage_my_process"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
	pkill -f "sudo -b sh manage_my_process"
	sudo -b sh manage_my_process
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
