#!/usr/bin/env bash
# configure nginx for another user
pkill -9 apache2
chmod 444 /etc/nginx/nginx.conf
sed -i '/#user www-data;/a user nginx;' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
su -c 'service nginx start' nginx
