#!/usr/bin/env bash
# configure nginx for another user
pkill -9 apache2
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server ipv6only=on/listen [::]:8080 default_server ipv6only=on/g' /etc/nginx/sites-available/default
service nginx restart
